version: '3.7'

services:
  app:
    restart: always
    container_name: scout
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
      target: app-container
    volumes:
      - ./scout:/app/scout
    ports:
      - "${PORT:-8000}:8000"
    environment:
      ENV: localdev
      SCOUT_SHOW_NEWSSPLASH: ${SCOUT_SHOW_NEWSSPLASH:-False}
      RESTCLIENTS_SPOTSEEKER_HOST: ${RESTCLIENTS_SPOTSEEKER_HOST:-""}
      SPOTSEEKER_OAUTH_KEY: ${SPOTSEEKER_OAUTH_KEY:-""}
      SPOTSEEKER_OAUTH_SECRET: ${SPOTSEEKER_OAUTH_SECRET:-""}
      RESTCLIENTS_SPOTSEEKER_DAO_CLASS: ${RESTCLIENTS_SPOTSEEKER_DAO_CLASS:-Mock}
      OAUTH_USER: ${OAUTH_USER:-javerage}
      SCOUT_SHOW_ALT_TECH: ${SCOUT_SHOW_ALT_TECH:-False}
      COMPRESS_ENABLED: ${COMPRESS_ENABLED:-True}


