autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
targetAverageUtilization: 100
resources:
  limits:
    cpu: 1.0
    memory: 1280Mi
  requests:
    cpu: 256m
    memory: 1024Mi
ingress:
  enabled: true
  tls:
    scout:
      secretName: prod.scout.uw.edu-ingress-cert
      hosts:
        - prod.scout.uw.edu
  hosts:
    scout:
      host: prod.scout.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16K"
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
externalService:
  enabled: true
  name: scout-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.196
  servicePort: 3306
database:
  engine: mysql
  name: scout_prod
  hostname: scout-db-service
  secretName: prod.scout.uw.edu-sql-secrets
repo: scout
instance: prod
image:
  repository: gcr.io/uwit-mci-axdd/scout
  tag: IMAGE_TAG
memcached:
  enabled: false
cronjob:
  enabled: false
environmentVariables:
  - name: CLUSTER_CNAME
    value: prod.scout.uw.edu
  - name: ENV
    value: prod
  - name: RESTCLIENTS_SPOTSEEKER_DAO_CLASS
    value: Live
  - name: RESTCLIENTS_SPOTSEEKER_HOST
    value: https://prod.api.scout.uw.edu
  - name: SCOUT_SHOW_NEWSSPLASH
    value: True
  - name: WEBSERVER
    value: nginx
externalSecrets:
  enabled: true
  secrets:
    - name: prod.scout.uw.edu-secrets
      externalKey: axdd/kv/data/scout/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: google-analytics-key
          property: google-analytics-key
        - name: spotseeker-oauth-key
          property: spotseeker-oauth-key
        - name: spotseeker-oauth-secret
          property: spotseeker-oauth-secret
    - name: prod.scout.uw.edu-sql-secrets
      externalKey: axdd/kv/data/scout/common/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    # may completely delete later if not needed
    # - name: prod.scout.uw.edu-ic-cert
    #   externalKey: axdd/kv/data/scout/prod/ic-certs
    #   data:
    #     - name: prod.scout.uw.edu-ic.cert
    #       property: prod.scout.uw.edu-ic.cert
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: prod.scout.uw.edu-secrets
    secretKey: django-secret
  googleAnalyticsKey:
    name: GOOGLE_ANALYTICS_KEY
    secretName: prod.scout.uw.edu-secrets
    secretKey: google-analytics-key
  spotseekerOauthKey:
    name: SPOTSEEKER_OAUTH_KEY
    secretName: prod.scout.uw.edu-secrets
    secretKey: spotseeker-oauth-key
  spotseekerOauthSecret:
    name: SPOTSEEKER_OAUTH_SECRET
    secretName: prod.scout.uw.edu-secrets
    secretKey: spotseeker-oauth-secret
